30-seconds/30-seconds-of-python

snippets/is_lower_case.md, snippets/is_upper_case.md, snippets/max_n.md
Variable names used in some snippets are reserved names which cause the name shadowing, so fixed the variable names.
=> fix: snippets reserved name shadowing

snippets/compact.md, snippets/difference.md
=> Fix some issues

snippets/average.md, static-parts/readme-start.md
fix typo mentioning python2 to python3
**Resolves** #32
=> [solves #32] fix typo

CONTRIBUTING.md
Fixed a typo in `CONTRIBUTING.md`
=> Fixed typo 

snippets/count_occurences.md
Changed  'an list' to 'a list' in 5th line.
=> Fixed a grammatical error.

snippets/is_upper_case.md
The return result in the documentation was incorrect (Did not match the actual return value of the code)
in 30-seconds-of-python-code/snippets/is_upper_case.md
```python
is_upper_case('a3@$') # False
```
in 30-seconds-of-python-code/snippets/is_upper_case.md
```python
is_upper_case('a3@$') # True
```
**Resolves** #71
=> [FIX: #71] wrong return value for is_upper_case("a3@$")

snippets/count_vowels.md
len() was used twice, which produced error. Fixed that.
Also included print() statements, so that the function call actually prints the no. of vovels.
=> Fixed error in code

README.md
=> Typo: "sring" -> "string"

.travis.yml, requirements.txt
fix travis build
fix travis build
=> fix travis build

snippets/is_anagram.md
Added a snippet that implements the `is_anagram` function.
=> [FEATURE] add is_anagram function

snippets/fibonacci.md
Adds a snippet for a "fibonacci" method that generates the fibonacci sequence in a list up to a given nth term
=> [FEATURE] Added fibonacci code snippet

snippets/bubble_sort.md, test/bubble_sort/bubble_sort.py, test/bubble_sort/bubble_sort.test.py
=> Pythonic sort bubble snippet

snippets/unique_elements.md
Added a snippet called `unique_elements` to get the unique elements of a given array
=> [FEATURE] Added snippet for getting unique elements in a list

snippets/max_n.md
Minor typo fix to fix missing backtick
=> [FIX] Fix quotation marks in max_n

snippets/camel.md
Simpler implementation for `camel`, removes regex with complex look-behind matching, replace with simpler string functions
=> [ENHANCEMENT] Simplify camel snippet

snippets/initialize_list_with_range.md
Remove list comprehension, use list constructor instead
=> [ENHANCEMENT] Remove list comprehension

package-lock.json, src/docs/pages/about.js, src/docs/pages/index.js
Added about section to the main page, changed import order style.
=> add about section on initial page, style sorting

snippets/flatten.md
Simple nested list comprehension script. I only added the script in the (to the best of my knowledge) proper formatting.
=> [FEATURE] Added Flatten() script to flatten lists of lists

snippets/initialiaze_2d_list.md, snippets/offset.md
=> Remove placeholder text

snippets/map_values.md
=>  [ENHANCEMENT] Replace for loop with one line dictionary comprehension

snippets/factorial.md
and is faster
```
>>> timeit.timeit('[x >= 0 and x % 1 == 0 for x in range(100)]', number=1000000)
5.681200352031738
>>> timeit.timeit('[x >= 0 & x % 1 == 0 for x in range(100)]', number=1000000)
7.641936696134508
```
=> [ENHANCEMENT] Use and instead of bitwise and

snippets/none.md
We can run function directly. `all` can iterate over by generator
=> [ENHANCEMENT] Remove redundant map

README.md, snippet_data/snippetList.json, snippet_data/snippets.json, snippets/n_times_string.md
=> add n_times_string snippet

snippets/snake.md
=> [FIX #116] Fix snake snippet

snippets/intersection.md
Change the intersection snippet to use built-in set functionality from python instead of list comprehension 
**Resolves** #124
=> [ENHANCEMENT] update intersection snippet

snippets/median.md
Finds the median of the list by finding the middlemost element after sorting it.  Uses the inbuilt sort function.
=> [FEATURE]Added a snippet that finds the median

snippets/filter_non_unique.md, snippets/filter_unique.md
add new 'filter_unique' function and definition
Resolves #123
=> 123 unique function fixing

snippets/cast_list.md
**Resolves** #(issue number) 
- [ * ] Enhancement (non-breaking improvement of a snippet)
=> fix cast_list

snippets/reverse_string.md
Snippet that reverses the string.
=> [FEATURE] Snippet that reverses a string

snippets/degrees_to_rads.md
Since the radians-to-degrees snippet exists, I added the opposite.
I added a python function that changes degrees to radians.
=> Added a degrees-to-radians snippet.

snippets/camel.md
I think there is no use of using space literal match (/s) in the pattern. So I removed it and updated the snippet and it's document accordingly. Please review it and let me know if I am wrong.
=> modified regexp and documentation

CONTRIBUTING.md
- [x ] General / Things regarding the repository (like CI Integration)
=> amend link formatting

snippets/camel.md
the regexp is not having any pattern to match a space. Hence changed the documentation accordingly.
=> updated documentation

snippets/median.md
=> Fix formatting and remove unnecessary else.

snippets/check_prop.md, snippets/compose.md, snippets/compose_right.md, snippets/curry.md, snippets/delay.md, snippets/unfold.md, snippets/when.md
Add 7 new snippets in the `function` category.
*Due by March 29, 2020* - See [Sprint 4 2020](https://github.com/30-seconds/30-seconds-web/milestone/8) in 30-seconds-web.
=> Add function snippets

snippets/median.md, snippets/sample.md, snippets/shuffle.md, snippets/split_lines.md, snippets/zip.md
**Resolves** #171; suggests using builtin functions for the following snippets:
- [median](https://www.30secondsofcode.org/python/s/median), 
- [sample](https://www.30secondsofcode.org/python/s/sample), 
- [shuffle](https://www.30secondsofcode.org/python/s/shuffle),
- [split_lines](https://www.30secondsofcode.org/python/s/split-lines) and
- [zip](https://www.30secondsofcode.org/python/s/zip).
=> [FIX: #171] Suggests using builtin functions

snippets/filter_non_unique.md, snippets/filter_unique.md
**Resolves** #170.
Uses a [`Counter`](https://docs.python.org/3/library/collections.html#collections.Counter) to get the amount of each value in the list. This improves the running time from O(n²) to O(n).
=> [FIX: #170] Improve filter functions

snippets/filter_non_unique.md, snippets/filter_unique.md
Fix typo when referencing `collections.Counter`.
=> Fix Counter typo

snippets/find_parity_outliers.md
Add a new snippet - `find_parity_outliers`.
=> Add find_parity_outliers

snippets/snake.md
=> [FIX] Typo in snake snippet

snippets/max_element_index.md
=> [FIX] Typo in max-element-index snippet

snippets/has_duplicates.md
=> Fix typo in has_duplicates

snippets/group_by.md
=> Update group_by expertise tag

for_each.md, for_each_right.md, frequencies.md, have_same_contents.md, includes_all.md, includes_any.md
=> New list snippets

snippets/is_contained_in.md, snippets/map_object.md, snippets/take.md, snippets/take_right.md
4 new snippets:
- `take`
- `take_right`
- `is_contained_in`
- `map_object`
=> List snippet additions

snippets/is_anagram.md
**Resolves #190**
The new snippet ignores punctuation, spaces and special (non-alphanumeric) characters.
Uses a `collections.Counter` to improve running time to O(n).
The example has also been changed to test the filtering of punctuation and special characters.
=> [FIX #190] Improves is_anagram

snippets/collect_dictionary.md, snippets/find_key.md, snippets/find_keys.md, snippets/invert_dictionary.md, snippets/merge_dictionaries.md, snippets/to_dictionary.md
- invert_dictionary.md
- collect_dictionary.md
- to_dictionary.md
- find_key.md
- find_keys.md
- merge_dictionaries.md
=> Add new snippets

snippets/filter_non_unique.md
=> bug fix in filter_non_unique.md

snippets/median.md
=> Modify return type for median function snippet

snippets/frequencies.md
1. Removed unused import
2. Provided precise implementation
3. Formatted example
=> Imrove frequencies snippet implementation

snippets/count_occurences.md
Since Python has something built-in for this exact purpose, we can rather use that.
=> Use Python's built-in count method to do the counting for us.

snippets/collect_dictionary.md
Using the `defaultdict` makes for better readability in the loop when the items are appended to the dict.
=> Collect Dictionary: better readability when appending to list

snippets/sum_of_powers.md
=> refactored sum_of_powers, Resolves #354

snippets/frequencies.md
=> Updated frequencies.md Resolves #362

snippets/bifurcate.md, snippets/chunk.md, snippets/geometric_progression.md
=> Refactor snippets `bifurcate`, `chunk` and `geometric_progression`. Resolves #391.

snippets/pluck.md
Adds the pluck snippet, to be used when the goal is to retrieve all values in `list` of `dicts` give a `key`.
=> Adds pluck

snippets/chunk_into_n.md, snippets/count_by.md, snippets/initial.md
=> Update `count_by`, `chunk_into_n` and `initial`
